# Generated by Django 4.0.4 on 2022-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMessage',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=999, null=True)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
