# Generated by Django 4.0.3 on 2022-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('Classify_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Classify_Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
