# Generated by Django 4.0.4 on 2022-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0005_alter_classify_classify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='Classify_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
