# Generated by Django 4.0.3 on 2022-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0006_alter_classify_classify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelModel',
            fields=[
                ('Label_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Label_Color', models.CharField(max_length=10, unique=True)),
                ('Label_Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Classify',
            new_name='ClassifyModel',
        ),
    ]
